version: '2'
services:
  web:
    image: creditas/rediscop-dev:alpha
    container_name: core
    restart: always
    working_dir: /var/app
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
    ports:
      - "3000:3000"
    environment:
      REDISTOGO_URL: redis://shared_redis:6379


networks:
  default:
    external:
      name: private_development_network
